def ridles():
    beginner = [
    {"question": "Я желтый, и я фрукт. Обезьяны любят меня. Что я такое?", "answer": "banana"},
    {"question": "Я красный, и я фрукт. Я расту на дереве. Что я такое?", "answer": "apple"},
    {"question": "Я белый, и я холодный. Ты можешь пить меня. Что я такое?", "answer": "milk"},
    {"question": "Я маленький, и я зеленый. Я живу в воде. Что я такое?", "answer": "frog"},
    {"question": "Я большой, и я серый. У меня длинный нос. Что я такое?", "answer": "elephant"},
    {"question": "Я круглый, и я оранжевый. Я расту в земле. Что я такое?", "answer": "carrot"},
    {"question": "Я маленький, и я желтый. Я могу летать. Что я такое?", "answer": "bee"},
    {"question": "Я большой, и я коричневый. Я живу в лесу. Что я такое?", "answer": "bear"},
    {"question": "Я маленький, и я черный. Я живу ночью. Что я такое?", "answer": "bat"},
    {"question": "Я большой, и я синий. Я живу в океане. Что я такое?", "answer": "whale"}
    ]


    intermediate = [
            {"question": "The more you take, the more you leave behind. What am I?", "answer": "footsteps"},
            {"question": "I’m not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "fire"},
            {"question": "I have keys but no locks. I have space but no room. What am I?", "answer": "keyboard"},
            {"question": "I’m tall when I’m young, and I’m short when I’m old. What am I?", "answer": "candle"},
            {"question": "What has to be broken before you can use it?", "answer": "egg"},
            {"question": "What has a heart that doesn’t beat?", "answer": "artichoke"},
            {"question": "What has hands but can’t clap?", "answer": "clock"},
            {"question": "I’m full of holes but still hold water. What am I?", "answer": "sponge"},
            {"question": "I can fly without wings. I can cry without eyes. What am I?", "answer": "cloud"},
            {"question": "I’m always in front of you but can’t be seen. What am I?", "answer": "future"},
            {"question": "What has a face but no head?", "answer": "clock"},
            {"question": "What has a neck but no head?", "answer": "bottle"},
            {"question": "What has to be broken before you can eat it?", "answer": "egg"},
            {"question": "What has a thumb and four fingers but isn’t alive?", "answer": "glove"},
            {"question": "What has a ring but no finger?", "answer": "phone"},
            {"question": "What has a bed but never sleeps?", "answer": "river"},
            {"question": "What has a head and a tail but no body?", "answer": "coin"},
            {"question": "What has a bark but no bite?", "answer": "tree"},
            {"question": "What has a tongue but can’t talk?", "answer": "shoe"},
            {"question": "What has a face but can’t smile?", "answer": "mountain"},
            {"question": "What has a bottom at the top?", "answer": "leg"},
            {"question": "What has a mouth but can’t eat?", "answer": "river"},
            {"question": "What has a key but can’t open locks?", "answer": "piano"},
            {"question": "What has a bed but never lies down?", "answer": "truck"},
            {"question": "What has a foot but no legs?", "answer": "snail"},
            {"question": "What has a head but never weeps?", "answer": "nail"},
            {"question": "What has a tail but no body?", "answer": "comet"},
            {"question": "What has a spine but no bones?", "answer": "book"},
            {"question": "What has a face but no eyes?", "answer": "clock"},
            {"question": "What has a heart but no organs?", "answer": "artichoke"},
            {"question": "What has a bank but no money?", "answer": "river"},
            {"question": "What has a trunk but no limbs?", "answer": "tree"},
            {"question": "What has a wave but no water?", "answer": "flag"},
            {"question": "What has a crown but no head?", "answer": "tooth"},
            {"question": "What has a needle but can’t sew?", "answer": "compass"},
            {"question": "What has a shell but isn’t a nut?", "answer": "turtle"},
            {"question": "What has a page but no words?", "answer": "book"},
            {"question": "What has a frame but no pictures?", "answer": "bicycle"},
            {"question": "What has a button but no shirt?", "answer": "doorbell"},
            {"question": "What has a screen but no movies?", "answer": "window"},
            {"question": "What has a handle but no door?", "answer": "cup"},
            {"question": "What has a blade but can’t cut?", "answer": "fan"},
            {"question": "What has a thread but no needle?", "answer": "spider"},
            {"question": "What has a root but no leaves?", "answer": "mountain"},
            {"question": "What has a bridge but no water?", "answer": "nose"},
            {"question": "What has a stage but no actors?", "answer": "microscope"},
            {"question": "What has a lock but no key?", "answer": "hair"},
            {"question": "What has a belt but no pants?", "answer": "car"},
            {"question": "What has a horn but doesn’t honk?", "answer": "rhino"}
        ]


    advanced = [

            {"question": "I am not alive, but I can die. What am I?", "answer": "battery"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "fire"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "map"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "pencil"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "future"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "flame"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "sponge"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "echo"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "keyboard"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "breath"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "tomorrow"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "shadow"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "blaze"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "atlas"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "graphite"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "horizon"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "smoke"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "net"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "whistle"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "typewriter"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "bubble"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "time"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "star"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "volcano"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "globe"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "charcoal"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "darkness"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "cloud"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "sieve"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "kite"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "calculator"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "thought"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "wind"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "candle"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "lava"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "chart"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "lead"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "fate"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "shadow"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "colander"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "flag"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "organ"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "dream"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "silence"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "moon"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "sun"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "blueprint"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "chalk"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "void"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "mist"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "sponge"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "song"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "piano"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "smoke"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "hope"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "mirror"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "inferno"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "diagram"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "graphite"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "destiny"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "fog"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "honeycomb"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "whisper"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "harpsichord"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "shadow"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "memory"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "statue"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "ember"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "scheme"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "clay"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "echo"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "dew"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "coral"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "breeze"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "synthesizer"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "spark"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "aura"},
            {"question": "I am not alive, but I can die. What am I?", "answer": "ice"},
            {"question": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "forge"},
            {"question": "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?", "answer": "layout"},
            {"question": "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?", "answer": "marble"},
            {"question": "I am always in front of you but can never be seen. What am I?", "answer": "infinity"},
            {"question": "I am not alive, but I can grow. I don’t have lungs, but I need air. What am I?", "answer": "vapor"},
            {"question": "I am full of holes but still hold water. What am I?", "answer": "sponge"},
            {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", "answer": "storm"},
            {"question": "I have keys but open no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", "answer": "accordion"},
            {"question": "I am light as a feather, yet no one can hold me for long. What am I?", "answer": "flame"},
            {"question": "I am always in front of you but can’t be seen. What am I?", "answer": "eternity"}

    ]
    return beginner, advanced, intermediate